Feat(frontend): Rename and modify the 'PhoneBrand' component to be more general
nfroidure/phone-coop pull request #30
Opened 2021-12-01 16:08 UTC by GuillaumeKESTEMAN

Rename the component : 'PhoneBrand' to 'Select' 
Modifications : make this component more general, now it's a general component which needs a title and an array of options

2021-12-01 16:53 UTC, nfroidure requested changes
Otherwise LGTM

2021-12-02 08:29 UTC, GuillaumeKESTEMAN commented on front/components/Select.tsx
> +        name="brand"
This has been added :+1:

2021-12-02 09:01 UTC, nfroidure approved these changes
LGTM

2021-12-02 09:02 UTC, nfroidure commented
Just squash the 2 commits into one and you're done ;). Congratz!

2021-12-07 08:31 UTC, merged